# Generated by Django 3.1.4 on 2021-04-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210419_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='time',
        ),
    ]
